### ISSUE TITLE
System Messages/Prompt Chains

### ISSUE THREAD

**Issue by babybirdprd** [pezzolabs/pezzo#100]
### Proposal

Not entirely sure how difficult it would be to add prompt chains to this. But do feel system messages are a necessity, given the new versions of OpenAI API released this month. Would love to see these features implemented at some point.

### Use-Case

Primary use case would be for prototyping more complicated AI products. Could allow for far more consistent responses. As far as I know there isn't anything like what I'm describing. Or at least I haven't come across any.

### Is this a feature you are interested in implementing yourself?

No

**Comment by arielweinberger** [comment]
Thanks @babybirdprd. We've been prototyping this idea for a while and could use your feedback. If you could ping me on Discord, I'd love to hear more about your use case and get your input on our design.

**Comment by arielweinberger** [comment]
Fixed in #205 and shipped in https://github.com/pezzolabs/pezzo/releases/tag/v0.6.1
