### ISSUE TITLE
Ability to delete an environment

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#123]
### Proposal

Currently we do not provide the ability to remove an environment. In this feature, the following needs to be implemented:

# Console
- Implement a delete button next to each environment (take an example from the organization members view)
- Upon clicking the button, a confirmation modal will appear with a message saying "Are you sure you want to delete the {{environment name}} environment? All associated data will be lost."
- Upon confirming, a GraphQL mutation `deleteEnvironment` will be sent

# Server
- Change the Prisma schema to support cascade deletion of anything that has a relation to an environment. I believe this is currently only the `PromptEnvironment` model, which represents a deployment of a prompt version. Simply put, this means that whenever you delete an environment, you will also delete its deployment (`PromptEnvironment` instances). This can be automated in Prisma, [see here](https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions).
- Implement the GraphQL mutation in the appropriate resolver/service (`identity/environments.resolver.ts`), validate that the user is an admin of their org (there are plenty of examples in the codebase).
- The environment will be deleted.

### Use-Case

Ability to delete environments in case they were created accidentally or aren't needed anymore.

# Note
Make sure you branch off of `release/0.4.0`, which is our next release.

**Comment by yehonatanyosefi** [comment]
I'd like to take this one please

**Comment by arielweinberger** [comment]
@yehonatanyosefi You got it! Anything you need, just let us know.

**Comment by arielweinberger** [comment]
Shipped in `0.4.0`. Thanks for your contribution @yehonatanyosefi!
