### ISSUE TITLE
Add OpenAPI spec to Pezzo's REST API

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#190]
### Proposal

It would be valuable to have an auto-generated OpenAPI spec for Pezzo's REST API.

- REST is used exclusively by our SDK clients (currently JS and Python), and would be a great way for anyone to integrate, regardless of whether there is an SDK available or not.
- All REST endpoints are defined in NestJS controllers (`*.controller.ts`) in the `apps/server` directory.
- Solution must use [@nestjs/swagger](https://docs.nestjs.com/openapi/introduction)

**Comment by senderh55** [comment]
I will take it

**Comment by arielweinberger** [comment]
Good luck. I'd like us to review it together because the impact is significant.
