### ISSUE TITLE
Add always-up-to-date REST API to the docs

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#191]
### Proposal

Depends on #190.

- Once we have an auto-generated OpenAPI spec (#190), we can insert it into our documentation site.
- Our docsite can be found in `/docs`.
- We use [Mintlify](https://mintlify.com/docs/quickstart). Mintlify has a feature for this. [Read more about it here](https://mintlify.com/docs/api-playground/openapi).

### Is this a feature you are interested in implementing yourself?

No

**Comment by SniperBuddy101** [comment]
I'd like to take this.

**Comment by SniperBuddy101** [comment]
@arielweinberger 
I'm trying to set this up. Unable to run the prisma migrations. Says that the authentication credentials are incorrect for Postgres.

**Comment by arielweinberger** [comment]
Hi @SniperBuddy101 it's possible that you haven't started Postgres using Docker Compose. Please check the READM.md and if you have any issues please share logs.

This task is blocked by an existing PR. I plan to review and merge it today/tomorrow and then this will be available.

Please do keep me posted about whether you managed to run Pezzo locally or not. If you did, happy to let you take it!

**Comment by SniperBuddy101** [comment]
@arielweinberger 
Understood. There was a process running on port 5433.
Was able to get pezzo working locally. Will work on this issue once the dependent PR is merged.

**Comment by arielweinberger** [comment]
@SniperBuddy101 Feel free to give it a shot. You can use the following endpoint which contains the API spec for now: https://api.staging.pezzo.ai/api/spec

And here are the docs on how to do it:
https://mintlify.com/docs/api-playground/configuration

No need for authentication/playground. Please try to finish this in the next 1-2 days, and keep me posted if you need any help/any delays. Good luck!
