### ISSUE TITLE
Update titles in the Pezzo Console

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#192]
### Proposal

Currently, all Console pages have the `Pezzo` title. This feature is about adding a title for all pages. The format should be as follows: `{feature} - Pezzo`.

Examples:
- Login page: `Login - Pezzo`
- Project Dashboard page: `Dashboard - Pezzo`
- Prompts page: `Prompts - Pezzo`
- Environments page: `Environments - Pezzo`
- ...etc

### Use-Case

This will provide a better user experience, and make it much easier to understand which Pezzo tab is most relevant by providing context at a glance.

### How to approach this

We have `usehooks-ts` nstalled. More specifically, you can use the [useDocumntTitle](https://usehooks-ts.com/react-hook/use-document-title) hook to change the title per page.

All pages can be found in a component with a `*Page.tsx` file name. E.g. `LoginPage.tsx`, `ProjectsPage.tsx` and so on.

**Comment by senderh55** [comment]
I will take it

**Comment by arielweinberger** [comment]
Assigned. I'm available her or on our [Discord](https://pezzo.cc/discord) if you need any help!
