### ISSUE TITLE
Prisma version conflict with Prisma client

### ISSUE THREAD

**Issue by jim123ture** [pezzolabs/pezzo#193]
### Report

prisma -v
Environment variables loaded from .env
prisma                  : 5.3.1
@prisma/client          : 5.1.1

### Steps to reproduce the problem

1.
2.
3.

### Logs (if applicable)

```
example
```

### How do you use Pezzo?

None

**Comment by arielweinberger** [comment]
Hi @jim123ture thanks for reporting. I see you're using `prisma` which might be using a global prisma installation. Can you try running `npx prisma -v` in the root of the Pezzo repository? This will use the version from the repo. This is what I get, which seems fine:

```
Environment variables loaded from .env
prisma                  : 5.1.1
@prisma/client          : 5.1.1
Current platform        : darwin-arm64
```

Additionally, are you facing any issues? If so, please elaborate with logs if possible. Thanks!

**Comment by jim123ture** [comment]
thanks alot
