### ISSUE TITLE
running with Docker-compose failed

### ISSUE THREAD

**Issue by jim123ture** [pezzolabs/pezzo#201]
### Report

following instruction: https://docs.pezzo.ai/introduction/docker-compose, I tried to docker-compose up. but failed: 
root@racknerd-954248:/home/pezzo# docker-compose up
Failed to load /home/pezzo/apps/server/.env.local: open /home/pezzo/apps/server/.env.local: no such file or directory

### Steps to reproduce the problem

1.
2.
3.

### Logs (if applicable)

```
root@racknerd-954248:/home/pezzo# docker-compose up
Failed to load /home/pezzo/apps/server/.env.local: open /home/pezzo/apps/server/.env.local: no such file or directory
```

### Pezzo version

0.5.9

### How do you use Pezzo?

Docker Compose

**Comment by arielweinberger** [comment]
Fixed in https://github.com/pezzolabs/pezzo/commit/2b3ed5add4b73ac27a0b0ed1cb525f6303cca171
