### ISSUE TITLE
Wrap all non-antd icons with `<Icon />` in Pezzo Console

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#203]
### Report

Currently, [Ant Design](https://ant.design/) is the main design system used in Pezzo Console.

However, it is very limited in terms of icons. That's why we also use [Heroicons](https://heroicons.com/) sometimes.

Until now, whenever we  used Heroicons, we had to sometimes adjust parameters like height, width and even margin to make them fit into Ant Design components.

Recently I learned  that the `@ant-design/icons` library exposes an `Icon` component which standardizes external icons so they feat neatly into components.

This task is about going through the React codebase and making the changes, and of course making sure it all looks good.

# Example

If this was a previous use case:

```tsx
import {  ChatBubbleBottomCenterIcon } from "@heroicons/react/24/outline";

// Somewhere in JSX
<ChatBubbleBottomCenterIcon width={18} height={14} style={{ marginBottom: "xyz" }} />
```

Make it like so:
```tsx
import {  ChatBubbleBottomCenterIcon } from "@heroicons/react/24/outline";
import Icon from "@ant-design/icons/lib/components/Icon";

// Somewhere in JSX
<Icon
  component={() => (
    <ChatBubbleBottomCenterIcon width={15} /> // Setting width to 15px seems to work well for most use cases
  )}
/>
```

Finding all usages should be as simple as searching the entire `apps/console` library for `from "@heroicons`.

**Comment by avelynhc** [comment]
Hi there! I'm interested in trying out this project.
