### ISSUE TITLE
Login screen is not responsive

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#207]
### Report

<img width="772" alt="image" src="https://github.com/pezzolabs/pezzo/assets/4976416/cb8ca116-5ad9-4fb9-9b29-b449fd8ec1ce">

### Expected behavior

On smaller screens, I expect the login page to show only the login panel with the fields rather than the art. This can be fixed in the `LoginPage.tsx` component, and is using TailwindCSS.

### Steps to reproduce the problem

1. Run the platform
2. Go to http://localhost:4200/login

### Pezzo version

0.6.1

### How do you use Pezzo?

None

**Comment by arielweinberger** [comment]
@0x00zer0day Done. Let me know if you need help!

**Comment by 0x00zer0day** [comment]
@arielweinberger Sure, thanks!

**Comment by 0x00zer0day** [comment]
@arielweinberger I have opened up a PR, please take a look.

**Comment by arielweinberger** [comment]
Reopening this as apparently the issue wasn't fixed.
