### ISSUE TITLE
Prompt Tester dialog errors when response is erroneous and switching display mode

### ISSUE THREAD

**Issue by clickspider** [pezzolabs/pezzo#209]
### Report

**Given**  I am user testing a prompt
**When** I click on the test button
**And** my API_KEY is empty
**And** the test ran
**Then** I get a Prompt Tester Dialog
**When** I change the "display mode" to "chat"
**Then** I get an empty white page (JS error)

<img width="1430" alt="image" src="https://github.com/pezzolabs/pezzo/assets/46437510/96adb1cf-fb0e-434c-b6f2-0aa94552f4dd">

### Expected behavior

The page should not be white. @arielweinberger can you elaborate on what you expect the product behaviour to be?

### Steps to reproduce the problem

As reported above.

Here is also a [video](https://www.loom.com/share/053a9ae3a9404482845f34da6ead2ce5).

### Logs (if applicable)

```
react-dom.production.min.js:189 TypeError: Cannot read properties of null (reading 'key')
    at index.js:82:18
    at index.js:175:56
    at Array.map (<anonymous>)
    at w4 (index.js:175:35)
    at Ea (react-dom.production.min.js:167:137)
    at El (react-dom.production.min.js:290:337)
    at xc (react-dom.production.min.js:280:389)
    at yc (react-dom.production.min.js:280:320)
    at vc (react-dom.production.min.js:280:180)
    at ac (react-dom.production.min.js:271:88)
```

```
const renderInnerItem = (item, index) => {
    if (!renderItem) return null;
    let key;
    if (typeof rowKey === 'function') {
      key = rowKey(item);
    } else if (rowKey) {
      key = item[rowKey];
    } else {
      key = item.key; // << here is the error
    }
    if (!key) {
      key = `list-item-${index}`;
    }
    return /*#__PURE__*/React.createElement(React.Fragment, {
      key: key
    }, renderItem(item, index));
  };
```

### Pezzo version

v0.6.1

### How do you use Pezzo?

Pezzo Cloud

**Comment by arielweinberger** [comment]
Fixed in #261
