### ISSUE TITLE
Sign up - password validation message is wrong

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#218]
### Report

![image](https://github.com/pezzolabs/pezzo/assets/4976416/6717f318-70f6-497c-80f9-3b54edbf4ff7)

The message doesn't mention that a special symbol is required.

### Expected behavior

The message should include the requirement of a special symbol.

### Steps to reproduce the problem

Go to the sign in screen, insert a password such as `As12223`.

### How do you use Pezzo?

None

**Comment by senderh55** [comment]
I will take it

**Comment by arielweinberger** [comment]
Assigned. I'm available her or on our [Discord](https://pezzo.cc/discord) if you need any help!
