### ISSUE TITLE
Functions in Report - UI could be improved

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#227]
### Report

When reporting an execution where a function has been called, we currently render the report like so:

![Screenshot 2023-10-02 at 18 09 50](https://github.com/pezzolabs/pezzo/assets/4976416/49a29ee9-5d04-4183-8d13-37d2b9e5d7cc)

This does not look good, and is hard to explore.

### Expected behavior

Render it in a more visually appealing way, the same as done in `Properties`. The JSON should be parsed and stringified with 2 spaces of indentation, to make it easier to read.

**Comment by senderh55** [comment]
@arielweinberger Can you assign it to me? I would like to take it.

**Comment by arielweinberger** [comment]
@senderh55 Go for it!
