### ISSUE TITLE
Cannot create a new prompt

### ISSUE THREAD

**Issue by deadsunrise** [pezzolabs/pezzo#237]
### Report

On a new self hosted docker-compose up, I cannot create a new prompt.  I can create projects, users, environments but prompts fails with error 

`Variable "$data" got invalid value { name: "Testing", integrationId: "openai", projectId: "clnlnlmky0004qs0iju0tr5yk" }; Field "integrationId" is not defined by type "CreatePromptInput".`

<img width="848" alt="Screenshot 2023-10-11 at 13 19 10" src="https://github.com/pezzolabs/pezzo/assets/11164/4ca0d49f-373e-41b8-bb13-fd75de95c35b">

### Expected behavior

Create the prompt correctly, it worked perfectly a while ago. 

### Steps to reproduce the problem

1.spin up new environment
2.create new proyect
3.try to create a ne Prompt

### Logs (if applicable)

```

```

### Pezzo version

main

### How do you use Pezzo?

Docker Compose

**Comment by arielweinberger** [comment]
Thanks for reporting @deadsunrise - will try to reproduce and come back. Can you check and see if you have any logs in the Pezzo Server?

**Comment by arielweinberger** [comment]
Hi @deadsunrise I am not able to reproduce this issue. Are you using Pezzo in development mode (so only spinning up the Pezzo infra via docker-compose) or the entire stack including the Server and the Client?

Try doing the following:
1. Delete any running Pezzo container
2. Delete any Pezzo volume
3. Run `docker-compose pull`
4. Run `docker-compose up`

And then try again. Let me know how it went.

**Comment by deadsunrise** [comment]
Hi Ariel, I was trying to follow https://docs.pezzo.ai/introduction/docker-compose 

I think I had old versions and the compose pull did the trick and updated some old container. I've nuked everything and restarted the process again and now it seems to be working perfectly. 

How is the update process supposed to be made? can I help documenting it?

Thanks for your help

**Comment by arielweinberger** [comment]
@deadsunrise For sure, feel free to submit a pull request. You'll need to fork the repo, clone your fork, then make the changes in the docs (you can find it in `docs/`), commit, push, and create a pull request so we can merge it back into Pezzo.

I'd be happy to include it as a Hacktoberfest contribution if you choose to do that. If you do, do sign up at [Hacktoberfest](https://hacktoberfest.com/).
