### ISSUE TITLE
Ability to delete provider API keys

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#238]
### Proposal

Currently, when we render API keys, we have a button to edit each API key. As #208 is in development, we'll need a way to allow customers to delete their API keys.

Simply add a red button with a trash icon (same as done in other places in the platform) that deletes an API key. Implement the API endpoint if it does not exist.

# Context
- Need to do some NestJS work (add a resolver mutation - `deleteProviderApiKey`, the service method already exists)
- React (add a button, GraphQL mutation definition + hook, call the resolver mutation)

### Is this a feature you are interested in implementing yourself?

Happy for interested community members to pick this up!

**Comment by adityapuri75** [comment]
@arielweinberger Please assign this issue to me.

**Comment by arielweinberger** [comment]
@adityapuri75 Good luck!

**Comment by adityapuri75** [comment]
hii @arielweinberger, I have created a PR for this issue please review
