### ISSUE TITLE
Test Field in Environment and Prompt accepting values with spaces

### ISSUE THREAD

**Issue by adityapuri75** [pezzolabs/pezzo#242]
### Report

If the textfield is empty while user is trying to saving the prompt or a Environment value the Validation working Fine but if we add only spaces in the textfield the it will accept the empty value and create a prompt or Environment with no Name.

https://github.com/pezzolabs/pezzo/assets/49858681/8c5299b6-22fd-45a7-926e-32d4b0bb96a3

### Expected behavior

It should not accept the empty values

### Steps to reproduce the problem

as suggested in the report

### How do you use Pezzo?

Pezzo Cloud

**Comment by AAKASHBANSAL96** [comment]
@adityapuri75 Can you please assign this to me?

**Comment by adityapuri75** [comment]
Hello @AAKASHBANSAL96 i am also a contributor, @arielweinberger can assign the issue.

**Comment by arielweinberger** [comment]
Fixed in #262
