### ISSUE TITLE
Support for deno

### ISSUE THREAD

**Issue by Maxim-Filimonov** [pezzolabs/pezzo#243]
### Proposal

I tried to import `@pezzo/client` in deno using the following syntax:
```
import { Pezzo, PezzoOpenAI } from 'https://esm.sh/@pezzo/client@0.4.16';
```
However it fails to download due to openai official not being deno compatible:
```
deno cache deps.ts
error: Module not found "https://esm.sh/v133/openai@4.12.1/denonext/resources.js".
    at https://esm.sh/v133/openai@4.12.1/denonext/openai.mjs:6:13494
```
Can peer dependendcy be removed and openAi client provided as argument to pezzo client? 

### Use-Case

I'd like to use pezzo in supabase functions environment which uses Deno runtime.

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by arielweinberger** [comment]
Hi @Maxim-Filimonov, will you be kind to try and make this work on a fork and share the results?

**Comment by arielweinberger** [comment]
This has been open for a while and we still don't see strong interest from the community. I'll close this for now.
