### ISSUE TITLE
Drag reorder of Prompt messages in the prompt editor

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#246]
### Proposal

- Add a drag handle for reach hat message (marked in red). Use the `HolderOutlined` [Ant icon](https://ant.design/components/icon) for this. This will be the handle for dragging, and will drag the entire message.
- Use the [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) NPM package to handle dragging and sorting.
- Make sure to reflect the the new order in the Antd form used to manage message (check out [this file](https://react-dnd.github.io/react-dnd/about)). Then it will automatically be saved correctly on the back-end.

<img width="1137" alt="Screenshot 2023-10-14 at 11 47 05 AM" src="https://github.com/pezzolabs/pezzo/assets/4976416/b8696011-c50b-48b9-869d-fd04993d8343">

**Comment by adityapuri75** [comment]
Please assign this issue to me

**Comment by arielweinberger** [comment]
Good luck @adityapuri75

**Comment by adityapuri75** [comment]
Hello @arielweinberger, i was able to implement drag and drop but the message can be dragged from anywhere within the message body. Dragging through the handle giving me some issues but i am trying to resolve that will update you here soon.
