### ISSUE TITLE
It is possible to have multiple projects with the same name for an org

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#255]
### Report

Currently it's possible to create two projects with the same name under the same org.

### Expected behavior

There should not be two projects with the same name under an org.

# How to solve
Add validation to the projects resolver that checks for an existing project for the same organization ID. If found, throw a `new ConflictException` with a descriptive error message such as `Project with the name ${name} already exists`.

The front-end has error handling already, so no need to do anything there.

### Steps to reproduce the problem

1. Create a project, name it "My Project"
2. Create another one with the same name

### Pezzo version

latest

### How do you use Pezzo?

Pezzo Cloud

**Comment by adithya-s-k** [comment]
hey @arielweinberger 

I got to know about this issue from Discord.
I'd like to take it on.

I wanted to check what the timeline is for the contribution cycle. When do you need this implemented by? I'm excited to work on this and contribute to the project. Let me know if you need any other information from me. Looking forward to hearing back!

**Comment by adityadeshlahre** [comment]
![image](https://github.com/pezzolabs/pezzo/assets/132184385/68161314-c203-4f79-842c-7b4b922dadac)

hey @arielweinberger :wave: 
seems like this issue is already been handled in latest version of PEZZO!
Thank you :smile:

**Comment by arielweinberger** [comment]
Indeed, seems like it's fixed. Closing this. @adithya-s-k ping me on Discord, we'll find you a task!
