### ISSUE TITLE
[BUG] spaces only can be used update/create

### ISSUE THREAD

**Issue by adityadeshlahre** [pezzolabs/pezzo#256]
### Report

**Only spaces can be entered and update in different places.**

### Expected behavior

**Should pop same error { error : it produces when name is empty }.**

i would like to work in this issue !
please assign this to me
thank you :smile:

### Steps to reproduce the problem

https://drive.google.com/file/d/1ypir0DdXo__VGj27OguVuvnrns47_uup/view?usp=drive_link

On main page after login
1 try to create project with only "            " spaces

On settings tab
1 try to update name with only "            " spaces

### Logs (if applicable)

```
example
```

### Pezzo version

https://app.pezzo.ai/

### How do you use Pezzo?

Pezzo Cloud

**Comment by arielweinberger** [comment]
@adityadeshlahre feel free to pick this up. Thanks for reporting.

**Comment by arielweinberger** [comment]
Fixed in #262
