### ISSUE TITLE
Sign in/up with google Error "Access blocked"

### ISSUE THREAD

**Issue by anthonyjgrove** [pezzolabs/pezzo#285]
### Report

Attempted to sign up with Google. Recevied error "Access blocked: pezzo.ai has not completed the Google verification process"

![Screenshot 2024-02-04 at 9 59 49 AM](https://github.com/pezzolabs/pezzo/assets/14151868/684b16a4-6f3d-4fdc-ae22-de916be99b94)

### Steps to reproduce the problem

1.
2.
3.

### Logs (if applicable)

```
example
```

### How do you use Pezzo?

None

**Comment by arielweinberger** [comment]
Where do you experience this? Pezzo Cloud or self hosted?

I just managed to sign up/sign in on Cloud (https://app.pezzo.ai).

**Comment by anthonyjgrove** [comment]
Cloud, maybe try with one that isnt associated with the developer account?

**Comment by arielweinberger** [comment]
You're right - managed to reproduce. I'm on it.

**Comment by arielweinberger** [comment]
@anthonyjgrove Should be fixed now.
