### ISSUE TITLE
Up-to-date Helm chart

### ISSUE THREAD

**Issue by Reintjuu** [pezzolabs/pezzo#289]
### Report

Is the Helm chart still up-to-date? I found a Helm chart on https://artifacthub.io/packages/helm/pezzo/pezzo, but the source doesn't seem accessible anymore: https://github.com/pezzolabs/pezzo-k8s.

### Expected behavior

An up-to-date Helm chart should be available.

### Pezzo version

latest

### How do you use Pezzo?

Kubernetes Deployment

**Comment by arielweinberger** [comment]
Hey @Reintjuu, we don't have an official Helm chart.

**Comment by Reintjuu** [comment]
Thanks for your quick reply. I noticed your name (@arielweinberger) on ArtifactHub, so I suppose there once was an official Helm chart, right? Did you decide to remove the source for the sake of Pezzo's cloud services?

What I'm asking is: could you re-open source https://github.com/pezzolabs/pezzo-k8s?

**Comment by arielweinberger** [comment]
@Reintjuu Indeed, we made this change for the sake of our cloud service. The chart we have in that repo is *very* outdated, so I don't think it will be of any value nor will it reflect the current state of our stack.

I'm not opposed at all to a community-led effort for public Pezzo charts. The stack is not that complex after all - Postgres, ClickHouse, NestJS and Supertokens for auth. In fact, the docker-compose file should make it very straightforward to develop these Helm charts.

However, we won't be driving this initiative officially for now, for two reasons:
1. We don't have the capacity to do that as a small team (public charts will introduce engineering overhead)
2. As a company, it is in our best interest to make Pezzo Cloud the obvious choice versus self-hosting

Again, not opposed at all to a community-led effort.
