### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Tamir198** [pezzolabs/pezzo#30]
Hey, After clocking the marked link:

![image](https://github.com/pezzolabs/pezzo/assets/34707669/2e875c66-eccc-4083-8987-b75a51d4c846)

I am getting page not found: 

![image](https://github.com/pezzolabs/pezzo/assets/34707669/af59635f-5ff3-43b0-8504-b559cd71cb7d)

**Comment by ItayElgazar** [comment]
Hey @Tamir198 

That's because that part is generated on the fly, and it's only generated locally for you, to get the relevant types. Did you try to follow the instructions?

**Comment by Tamir198** [comment]
Got it, my mistake
