### ISSUE TITLE
Token refresh does not work in the middle of a session

### ISSUE THREAD

**Issue by arielweinberger** [pezzolabs/pezzo#43]
The way Supertokens works, is that whenever you get an Unauthorized status code, it'll try to refresh your token automatically.

With GraphQL, every response is a 200 response, therefore this Supertokens mechanism does not work. We need to intercept GraphQL response errors, and if the code is `UNAUTHORIZED`, try to manually refresh the token. If that fails, we manually sign the user out (refresh token is likely expired).

**Comment by AyanDas348** [comment]
Can you provide instructions on how to get started with this. Thanks!

**Comment by arielweinberger** [comment]
Let's finish the other one first? This one is quite a bit more complicated.

**Comment by arielweinberger** [comment]
@AyanDas348 since this is an urgent bug, I took it myself and fixed it at #48

**Comment by AyanDas348** [comment]
@arielweinberger Alright, please let me know if there is anything else I can work on
