### ISSUE TITLE
Circular dependencies in monorepo

### ISSUE THREAD

**Issue by overbit** [pezzolabs/pezzo#61]
### Report

The current configuration of the monorepo contains 2 circular dependencies.
This setup would cause unexpected results and potentially cause race build conditions

![image](https://github.com/pezzolabs/pezzo/assets/2861984/03c81660-d5a6-4bf2-9953-60339478dc0a)

### Expected behavior

Libraries must not depends on applications and applications should not depends on other applications.

The correct setup would be:
graphql <- console
graphql <- client <- console
graphql <- server

### Steps to reproduce the problem

Check the nx graph running `npx nx affected:graph` and select all projects

### How do you use Pezzo?

None

**Comment by arielweinberger** [comment]
Thanks for reporting @overbit. We're going to remove the `graphql` library altogether and utilize `codegen` to generate the types inside `apps/console`, to eliminate this circular dependency. Will close this issue as soon as it's fixed.

**Comment by arielweinberger** [comment]
Fixed in #72
