### ISSUE TITLE
Prompt Variables Unpredictable behaviors  

### ISSUE THREAD

**Issue by ericflecher** [pezzolabs/pezzo#63]
### Report

**Starting point** 
A basic prompt with a single variable
<img width="673" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/9e982554-e6be-4110-a71a-308b44d5c983">

**Inital test** 
 A null value in user_message returns "Hello! How can I assist you today?"
<img width="597" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/f2f12df3-9d1b-4067-b76f-0402ba162c83">

**Editing reqest**
- Added "Alive? " to the reqeust 
- Result gives a respose cosistent to what I would expect. 
<img width="577" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/b2c20af2-5fd4-466c-b29b-1bdf5828ffbc">

Using the variable to pass in "Alive?"
- "Alive?" does not seem to be passed to OpenAI
<img width="600" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/9d4d4b3f-e4d7-4da8-8034-2390c95188b6">
- Sending ping
<img width="592" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/acdbc250-bf22-4c2e-86e7-417aa20263fd">

### Expected behavior

I'm expecting the variable to be passed to the AI service. It does not apear that it is happening. 

### Steps to reproduce the problem

1.
2.
3.

### Logs (if applicable)

```
example
```

### How do you use Pezzo?

None

**Comment by ericflecher** [comment]
Thanks for the quick response!

@ItayElgazar  - I started out with more complex statements (screenshots below). "Return the state capital for the state provided: {{state}}"
**Null scenario**
<img width="838" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/72d5a721-efed-4bd6-b2fe-1819c6dcec3a">

Ohio in the request (bypassing the variable)
<img width="1196" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/1ce2baf6-7d3a-4601-82ee-a845de2205b0">


Ohio in variable with {{state}}
<img width="841" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/7dd6e479-680f-4ea2-a4ab-1490eb525216">

Ohio with variable {state}
<img width="1187" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/136abe9b-e93e-44aa-9f22-06d85b86aab7">

Using one bracket {ohio}, the variable does not show up in the variable section
<img width="1508" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/47f14e95-68ba-4292-9b52-be4b79334e54">

@arielweinberger 
- Showing the variables in the request would be incredibly helpful in helping me understand what is actually being sent to OpenAI
- Screenshot below using 
"You are a kind human who greets people. Greet a new user who signed up for our platform. Their name is {name}."
<img width="1511" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/edda0ac5-d2c9-4895-a26e-58d288009b87">

and, screenshot below using 
"You are a kind human who greets people. Greet a new user who signed up for our platform. Their name is {{name}}." I get a variable name but the same result as the prompts above. Note that, for some reason, the request was showing my past prompts. I had to refresh the page to start over. 
<img width="1207" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/fdcbb563-b80d-4468-b3a7-d9fce5ccc042">

<img width="1212" alt="image" src="https://github.com/pezzolabs/pezzo/assets/252245/a2474929-d87d-4d90-aa22-456dcfd5da6f">

**Comment by arielweinberger** [comment]
I see what's happening. It's related to our upcoming 0.1.0 release where the interpolation API has changed from using {} to using {{}}.

Good that you let us know. We'll merge the release branch today and then this issue will be fixed.

Once again, thanks for bringing this to our attention.

**Comment by ericflecher** [comment]
Happy to help. Keep up the great work.

**Comment by ericflecher** [comment]
Have you updated the docker image? I just tried, getting the same UI.
