### ISSUE TITLE
Unable to build docker image on MacOS docker desktop

### ISSUE THREAD

**Issue by DatMousii** [pezzolabs/pezzo#64]
### Report

Running on MacOS I've been attempting to build the docker image provided in the install instructions and encountering an issue preventing it from starting correctly:

dependency failed to start: container pezzo-bold_shtern-pezzo-server-1 is unhealthy
exit status 1

### Expected behavior

For docker desktop to compile and build

### Steps to reproduce the problem

1. download repository via macOS terminal and git build
2. docker-compose build the application

### Logs (if applicable)

```
ontainer pezzo-bold_shtern-supertokens-1  Created
 Container pezzo-bold_shtern-postgres-1  Created
 Container pezzo-bold_shtern-pezzo-server-1  Creating
 Container pezzo-bold_shtern-pezzo-server-1  Created
 Container pezzo-bold_shtern-pezzo-console-1  Creating
 Container pezzo-bold_shtern-pezzo-console-1  Created
 Container pezzo-bold_shtern-supertokens-1  Starting
 Container pezzo-bold_shtern-app-1  Starting
 Container pezzo-bold_shtern-postgres-1  Starting
 Container pezzo-bold_shtern-influxdb-1  Starting
 Container pezzo-bold_shtern-app-1  Started
 Container pezzo-bold_shtern-influxdb-1  Started
 Container pezzo-bold_shtern-supertokens-1  Started
 Container pezzo-bold_shtern-postgres-1  Started
 Container pezzo-bold_shtern-postgres-1  Waiting
 Container pezzo-bold_shtern-postgres-1  Healthy
 Container pezzo-bold_shtern-pezzo-server-1  Starting
 Container pezzo-bold_shtern-pezzo-server-1  Started
 Container pezzo-bold_shtern-pezzo-server-1  Waiting
 Container pezzo-bold_shtern-pezzo-server-1  Error
dependency failed to start: container pezzo-bold_shtern-pezzo-server-1 is unhealthy
exit status 1

```

### How do you use Pezzo?

Docker Compose

**Comment by arielweinberger** [comment]
Thanks for reporting. Most of the maintainers work on macOS so we're not sure why that would be an issue.

Can you try to run dependencies and run 'npx nx docker:build server' and let me know the output?

**Comment by arielweinberger** [comment]
We've just release `v0.1.0` of Pezzo in which we expect this issue to be fixed. Closing this, please let us know if the issue persists.
