### ISSUE TITLE
Variables aren't saving

### ISSUE THREAD

**Issue by mgunnin** [pezzolabs/pezzo#66]
### Report

When creating a new variable in the prompt, all of the existing variables return to "null". 

Additionally, after running the prompt test, any of the variables that are edited aren't saved and are also returned as "null".

### Pezzo version

May 28th, 2023

### How do you use Pezzo?

Docker Compose

**Comment by arielweinberger** [comment]
Thanks for reporting @mgunnin - we'll handle it ASAP.

**Comment by arielweinberger** [comment]
@mgunnin Just letting you know that the 2nd issue you reported was fixed yesterday as a part of our `v0.1.x` release. Regarding the 1st issue, we're on it.

**Comment by ItayElgazar** [comment]
Merged, will be released in the next version 🙏

**Comment by mgunnin** [comment]
Good work!
