### ISSUE TITLE
add organization parameter for OpenAI executor

### ISSUE THREAD

**Issue by evereq** [pezzolabs/pezzo#70]
### Proposal

In the `ExecutorOptions` needs to add the `organization` field and use it in the initialization of OpenAIApi Configuration https://github.com/pezzolabs/pezzo/blob/main/libs/integrations/src/lib/integrations/openai/executor.ts#L12 and https://github.com/pezzolabs/pezzo/blob/main/libs/integrations/src/lib/integrations/openai/sdk.ts#L4

### Use-Case

We are using multiple organizations in OpenAI :)

### Is this a feature you are interested in implementing yourself?

Maybe

**Comment by arielweinberger** [comment]
Thanks for reporting @evereq. I'd love to hear more about your use case. Would you mind joining our [Discord](https://discord.gg/h5nBW5ySqQ) and pinging me there?

**Comment by arielweinberger** [comment]
Oh, now I understand what you mean! You are talking about an OpenAI organization (thought you meant a Pezzo organization). We can get that done and released today.

**Comment by arielweinberger** [comment]
@evereq This should now be live at `@pezzo/integrations@0.1.4`.

**Comment by evereq** [comment]
@arielweinberger thanks a lot for the fast turnaround, it works! 🚀 

Btw, there is another potential place where to add an Organization selector in OpenAI and this time it's in the console app, e.g. could be a good place to add it below "Model" selector, so when you run some prompt from UI you can select OpenAI org too:

![image](https://github.com/pezzolabs/pezzo/assets/118497/db958035-b040-4d02-94e8-957e7c0ec10d)

In addition, maybe a good idea to add that to Provider API Keys page as the "Organization" field (next to OpenIA API key field):

![image](https://github.com/pezzolabs/pezzo/assets/118497/e7aa4f2d-1e53-4df2-8c63-d6159ee968cf)

The page also can be renamed to "Providers" because essentially it will manage not only API keys but other parameters relevant to each provider etc.

Anyway, for us it was important mainly to be able to select Org from the code, but I think for some it will be useful to be able to work with different OpenAI Orgs from UI too...
