### ISSUE TITLE
open ai key not saving on m1 mac pro 

### ISSUE THREAD

**Issue by VinnyChase28** [pezzolabs/pezzo#85]
### Report

I'm trying to enter my API key into the box:

<img width="1113" alt="image" src="https://github.com/pezzolabs/pezzo/assets/50678382/8e0eb472-279a-4763-b45b-f590e5c0f1f8">

I put that same API key into AI21 and it works. 

### Expected behavior

the api key for openai gets set. 

### Steps to reproduce the problem

1. set up project with docker on m1 mac pro
2. open console sign in
3. try to put API key for openai 

### Logs (if applicable)

```
example
```

### Pezzo version

latest

### How do you use Pezzo?

Docker Compose

**Comment by ItayElgazar** [comment]
Hi @VinnyChase28,

Thanks for the report! Investigating now.

**Comment by ItayElgazar** [comment]
Issue resolved. @VinnyChase28 used an old image. If you encounter this, try to docker-compose pull and make sure you're using the latest version.
