### ISSUE TITLE
prisma migration not executing properly and not providing logs

### ISSUE THREAD

**Issue by VinnyChase28** [pezzolabs/pezzo#86]
### Report

`vince.gauthier@Vince-Gauthier-MacBook-Pro:~/Desktop/pezzo$ npx dotenv-cli -e apps/server/.env -- npx prisma migrate deploy --schema apps/server/prisma/schema.prisma

Environment variables loaded from .env
Prisma schema loaded from apps/server/prisma/schema.prisma
Datasource "db": PostgreSQL database "pezzo", schema "public" at "localhost:5432"

11 migrations found in prisma/migrations

Error: P3009

migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `20230519223302_add_projects` migration started at 2023-06-15 18:12:37.505388 UTC failed with the following logs:

`

### Expected behavior

the migration happens successfully

### Steps to reproduce the problem

1.
2.
3.

### Logs (if applicable)

```
example
```

### How do you use Pezzo?

Local Development Setup

**Comment by ItayElgazar** [comment]
Issue resolved. @VinnyChase28 used an old image. If you encounter this, try to docker-compose pull and make sure you're using the latest version.
