### ISSUE TITLE
`CONTRIBUTING.md` is unavailable

### ISSUE THREAD

**Issue by tool3** [pezzolabs/pezzo#97]
### Report

There is a broken link in `README.md` which makes it a bit hard to contribute :) 

README excerpt:
> Please check out [CONTRIBUTING.md](https://github.com/pezzolabs/pezzo/blob/main/CONTRIBUTING.md) before contributing.

### Expected behavior

I expect to see how one would contribute to this repo

### Steps to reproduce the problem

1. open github.com
2. search for pezzo
3. try to contribute

### Logs (if applicable)

```
example
```

### How do you use Pezzo?

None

**Comment by arielweinberger** [comment]
Thanks for reporting @tool3! We'll be on it right away. In the meantime, if you want to contribute, feel free to hop on our [Discord](https://discord.gg/h5nBW5ySqQ) and ping me. There's plenty of exciting stuff to do ;)
