### ISSUE TITLE
get all prompts and add a description to them

### ISSUE THREAD

**Issue by VinnyChase28** [pezzolabs/pezzo#98]
### Proposal

simple query/function to get all prompts by the environment. if we have descriptions as well, on the client side it will be easy to know what the prompt will do when you execute it without even being in pezzo. 

### Use-Case

this would allow passing these as variables to pezzo functions and show all available prompts client side. 

### Is this a feature you are interested in implementing yourself?

yes

**Comment by arielweinberger** [comment]
Thanks @VinnyChase28. Is your use case API-based or UI-based? Do you want to view this information at an org level, or a project level?

I think an optional description is a good idea regardless.

**Comment by VinnyChase28** [comment]
Both. You could loop over a set of prompts by prompt name, and then also show the prompts and their description as cards in a UI.

**Comment by arielweinberger** [comment]
I'm not planning to implement this for now - there does not seem to be strong feedback from the community about this one.
